version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  order-service:
    build: ./services/order-service
    container_name: order-service
    depends_on:
      - rabbitmq
    volumes:
      - ./events:/events
    environment:
      RABBITMQ_URL: "amqp://rabbitmq"

  dispatch-service:
    build: ./services/dispatch-service
    container_name: dispatch-service
    depends_on:
      - rabbitmq
    volumes:
      - ./events:/events
    environment:
      RABBITMQ_URL: "amqp://rabbitmq"

  inventory-service:
    build: ./services/inventory-service
    container_name: inventory-service
    depends_on:
      - rabbitmq
    volumes:
      - ./events:/events
    environment:
      RABBITMQ_URL: "amqp://rabbitmq"
